### PR TITLE
Only target fullscreen videos

### PR DESCRIPTION
**Pull request by ngryman**
Hey @clundie, first thanks so much for this extension. I was switching to another browser each evening because of this bug 👍 

I was curious about how you achieved this and I got it, you give it a layer. Still you do this for every video of every page. This PR only targets fullscreen videos so your plugin only comes in when specifically needed.

Thanks!

### CODE REVIEW

**Comment by clundie** [comment]
@ngryman Thanks for the pull request. I found that the `video:fullscreen` selector does not work, because Chrome only understands `:-webkit-full-screen`, not `:fullscreen`. I verified in the developer console that the rule was not being applied, and artifacts still appeared in the video. The idea is good though, and I've reopened this here: https://github.com/clundie/VideoFixer/pull/3

**Comment by clundie** [comment]
The other problem was that `video:fullscreen` (and `video:-webkit-full-screen`) didn't match on the sites I tested (YouTube and Netflix) because the `video` element itself is not full screen; you have to match a `div` higher up in the tree; so in #3 I added a selector that matches when the video is a descendant of a full-screen element.

**Comment by clundie** [comment]
@ngryman I added you to the contributors list and made a new release. Thanks!

**Comment by ngryman** [comment]
Thanks for the clarifications 👍 and the new release 🎉

**Pull request closed without merging**
